### ISSUE TITLE
Hyprland crash on 'clear' confirmation dialog

### ISSUE THREAD

**Issue by envolution** [nwg-piotr/nwg-clipman#2]
Steps to reproduce:

- click clipboard icon in panel
- click clear
- move mouse inside confirmation dialog

<hyperland crash>

[hyprlandCrashReport15912.txt](https://github.com/user-attachments/files/15831073/hyprlandCrashReport15912.txt)

**Comment by nwg-piotr** [comment]
Hyprland 0.41.0 crashes for many various reasons. See NOTE here: https://github.com/nwg-piotr/nwg-shell/discussions/348

**Comment by nwg-piotr** [comment]
Fixed in [fe30e02a7a97665ebf87ae78f781e9bfb3706a42](https://github.com/nwg-piotr/nwg-clipman/commit/fe30e02a7a97665ebf87ae78f781e9bfb3706a42).
